# Generated by Django 5.2.14 on 2026-05-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Optional icon name, e.g. 'book', 'music', 'star'",
                max_length=50,
            ),
        ),
    ]
