# Generated by Django 5.2.14 on 2026-05-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Optional icon image for the category.",
                max_length=50,
                null=True,
                upload_to="category_icons/",
            ),
        ),
    ]
